name: spacefood
services:
  db:
    restart: always
    container_name: spacefood_db
    image: postgres:latest
    env_file:
      - ./.env
    ports:
      - "5431:5432"
    volumes:
      - spacefood-vol:/var/lib/postgresql/data

    networks:
      - main
  api:
    restart: always
    container_name: spacefood_api
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "2999:3000"
    networks:
      - main

networks:
  main:
    driver: bridge
    external: true
volumes:
  spacefood-vol:
    external: true
